---
openapi: 3.0.0
info:
  title: Simple Example
  version: "{{ version }}"
paths:
  "/":
    get:
      responses:
        '200':
          description: Index
          content:
            text/html:
              schema:
                type: string
